gekko:
  enabled: true
  image:
    tag: latest
  service:
    type: NodePort
    nodePorts:
      http: "30300"
  config:
    GEKKO_API_HOST : "127.0.0.1"
    GEKKO_API_PORT : 3000
    GEKKO_API_TIMEOUT : 120000
    GEKKO_ADAPTER : "mongodb"
    GEKKO_MONGODB_CONNECTION: "mongodb://gekko:gekko@platform-mongodb:27017/gekko"

mongodb:
  enabled: true
  # Auth Configuration
  usePassword: true
  mongodbRootPassword: root
  mongodbDatabase: gekko
  mongodbUsername: gekko
  mongodbPassword: gekko

  # Expose NodePort Locally
  service:
    type: NodePort
    nodePort: 31072

  # Disable persitence when runnin locally
  persistence:
    enabled: false

mongoclient:
  enabled: true
  service:
    type: NodePort
  ingress:
    enabled: false

redis:
  enabled: false
  cluster:
      enabled: false
  master:
    usePassword: false
    # password: 'set if true'
    service:
      type: NodePort
      nodePort: 31679
    persistence:
      enabled: false
